### ISSUE TITLE
Jets 6 Jobs not being created

### ISSUE THREAD

**Issue by SteffanPerry** [rubyonjets/jets#726] opened 2024-05-26 10:10 UTC
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         |  |
| ---------------- | ------- |
| Operating System | osx |
| Jets             |6.0|
| Ruby             |3.3.0|

---

## Expected Behaviour

When jobs are enabled via 
`config.job.enable = true` in deploy.rb, the jobs in app/jobs/* will be deployed.

## Current Behavior

After enabling jobs, none of the jobs in the app/job/directory have been created. This is using the latest rails 7.x, ruby 3.3.0, and jets 6.0

## Step-by-step reproduction instructions

Create a rails/jets application.
Create a api endpoint
Deploy the api
add a job (active job) and enable jobs in the deploy.rb config.
deploy jets again.

**Comment by jeremiahlukus** [comment] 2024-05-26 12:14
Do you have a sample application? 

Is the event lambda and sqs being created?

**Comment by jeremiahlukus** [comment] 2024-05-26 12:55
Tried on a couple different apps unable to reproduce.

**Comment by SteffanPerry** [comment] 2024-05-26 12:57
Thanks for taking a look. I'm gonna destroy everything then bring it back up to see if I can repro as well. 

But no the sqs and lambdas are not being created.

**Comment by jeremiahlukus** [comment] 2024-05-26 13:01
Did you set ?

config.active_job.queue_adapter = :jets_job

https://docs.rubyonjets.com/docs/jobs/

**Comment by tongueroo** [comment] 2024-05-27 06:02
@SteffanPerry Thanks for the report. Found some edge case issues with jobs. Will take a closer look soon. Just wanted to let you know so you don’t spin cycles.

**Comment by tongueroo** [comment] 2024-05-27 19:20
The edge case issues should be fixed. Fixed in #727 

For posterity:

* Needed to deploy jets twice because the sql queue url was being set in the lambda function at build vs lazily at cfn deployed time.  So it was set upon the 2nd and future deploys, hence it wasn’t reproduced on the jets deployments with job enable. They’ve been running on production for over a month 🎉
* It’s fixed now. The 1st deploy with job.enable will just work
* You should also update to the latest jets-rails plugin
* Lastly, jets jobs docs updated https://docs.rubyonjets.com/docs/jobs/enable/

**Closed by tongueroo** 2024-05-27 19:20 UTC
Labels: bug
